// SHOEY CHUG roast bank. {T}=team, {t}=time in seconds, {s}=spews. Rules: football/fantasy/chugging/league life only.
// No race, sexuality, family or appearance. No slurs. Nobody gets called "champ" and nobody gets a trophy.
var ROAST={
G:[
"{T} chugged like a backup kicker on a minimum deal: technically present, completely fucking useless.",
"That shoey had more drops than {T}'s waiver wire.",
"{t}s. My fantasy team scores faster than that, and my fantasy team is dogshit.",
"{T} drinks beer like they draft: slow, confused, and somehow worse than autodraft.",
"Sleeper just sent a push alert: {T} is QUESTIONABLE. At chugging. And at life.",
"You chug like you set lineups: three hours late with a QB on bye.",
"Most effort {T} has put in since the startup draft, and it still sucked.",
"That beer went down slower than {T}'s dynasty value, and that thing is in free fall.",
"Congrats, you finished. So does every 1-13 team. Eventually.",
"{T}, it's a shoey, not a sippy cup. Open your goddamn throat.",
"You drank that like you were paying for it. You weren't. Chug, you cheap bastard.",
"The cheerleaders filed a formal grievance with the commish over that performance.",
"{t} seconds of pure, uncut mediocrity. On brand for a franchise that's been mid since 2021.",
"That chug had the urgency of a GM sitting on six firsts doing absolutely nothing with them.",
"You mash that screen like you mash the trade button: wildly, constantly, zero results.",
"{T}'s throat has worse vision than their scouting department.",
"Even the sneaker looked embarrassed to be anywhere near your mouth.",
"Bench that liver. It's putting up kicker numbers.",
"Slowest thing I've seen since {T}'s last trade negotiation. Eleven counteroffers for a 3rd.",
"Pound for pound, the shoe drank more of you than you drank of it.",
"You chug like a rookie tight end: invisible, disappointing, and allegedly worth the wait.",
"Your liver just requested a trade to a contender.",
"{T} drinks like a handcuff RB: only useful if somebody else gets hurt.",
"Waiver-wire drinker. Somebody pick up a guy who can actually swallow.",
"That shoey was a 4th-round rookie pick. Nobody expected shit and you still underdelivered.",
"The league chat is already screenshotting this. Godspeed, {T}.",
"Even the insole had a better night than you.",
"You chugged like Sleeper at 12:59 on a Sunday: slow, glitchy, and full of excuses.",
"Hell of an effort. Terrible result. That's {T}'s whole dynasty in one beer.",
"If chugging were a stat you'd be a deep bench stash. In a 10-team league.",
"That chug was a punt on 4th and 1. Cowardly and slow.",
"You call that a shoey? Decaf goes down faster at a Monday morning meeting.",
"Your gag reflex has more starts than your WR2.",
"{T}: elite at losing, mediocre at drinking, somehow worse at fantasy.",
"Shotgun formation? More like shit-gun formation.",
"That chug was a fair catch. Nobody paid to watch that shit.",
"In {T}'s league, PPR stands for Pathetic Per Round.",
"Somebody check {T}'s pulse. And their roster. Both are flatlining.",
"You chugged with the pace of a 31-year-old RB on a snap count.",
"You don't need another beer, {T}. You need a trade partner who pities you.",
"Hydration: elite. Chugging: ass.",
"Your mouth has fewer completions than a rookie QB in a snowstorm.",
"The shoe tastes like feet. Your season tastes like defeat.",
"This shoey has been placed on IR due to a lack of effort.",
"You chug like you check scores: through your fingers, terrified.",
"Somewhere Jeremiah Smith just unfollowed {T}.",
"League rules say that dogshit attempt earns you another shoey. Line it up.",
"That shoey had more stoppages than a fourth-quarter replay review.",
"The beer asked for a trade. It wants to go somewhere it's appreciated.",
"That was a two-yard dump-off on 3rd and 12. Absolute cowardice.",
"You treat beer like your FAAB: hoard it all and blow it at the worst possible moment.",
"Your swallow has a lower floor than your RB3.",
"{T} drinks from the shoe the way they run a roster: face full of foam, no plan.",
"Fire the coordinator. Fire the GM. Fire whoever the hell taught you to drink.",
"Fun fact: {T}'s chug time and {T}'s playoff odds are both terrible.",
"That chug just got flagged for delay of game.",
"That's not a chug, that's a sad little sip with a marketing department.",
"Even autodraft knows how to finish something.",
"The shoe just dropped you to waivers. You clear Wednesday.",
"Your throat is running a prevent defense. Nothing's getting through.",
"That was the chugging version of starting a guy on bye. Embarrassing as hell.",
"Slower than the commish approving a trade, and that's slow as shit.",
"Your liver has better numbers than your lineup, and your liver is losing.",
"Beer isn't a two-minute drill, {T}. Then again, you'd fuck that up too.",
"That chug has strong 'pick swap in 2031' energy.",
"{T} drinks like they tank: on purpose, badly, and for way too long.",
"You sipped. In a shoe. In front of the whole league. Unforgivable.",
"That chug was a Thursday Night Football game: nobody wanted it and it was hard to watch."
],
FAST:[
"{t}s. Holy shit. Now do literally anything right on Sunday.",
"Fast as hell, {T}. Too bad they don't give fantasy points for swallowing.",
"Best thing {T} has done all season. Enjoy it, it won't last.",
"Elite chug. Bum roster. Pick one, apparently.",
"{T} finally drafted something good: a liver.",
"Fastest you've moved since you sprinted to accept a lopsided trade.",
"Absolute animal. The cheer squad is losing it. Your playoff odds are not.",
"Speed like that should be illegal. So should your lineup decisions.",
"{t}s. Somebody call the league office, {T} is cheating at beer.",
"Your throat is a first-ballot Hall of Famer. The rest of your team is a practice squad."
],
SLOW:[
"{t}s?! Snails just filed a complaint for being compared to you.",
"The cheerleaders aged a full season watching that.",
"A full quarter to finish one shoe. The two-minute warning came and went.",
"By the time you finished, waivers cleared twice.",
"That was so slow the beer went flat out of spite.",
"Slower than a Thursday night game between two 2-8 teams.",
"{t}s. Even the foam fell asleep.",
"Get your fucking throat checked, there's a traffic jam in there.",
"The crowd left early to beat traffic.",
"{T} chugs like the third string QB warms up: slowly, and for no reason."
],
SPEW:[
"You spewed on the cheerleaders, {T}. They're pressing charges and so is the league.",
"Projectile shoey. Somebody hose down the sideline.",
"{s} spew(s). You fumbled a beer. A BEER.",
"That wasn't a chug, that was a goddamn fire hydrant.",
"That beer came back up faster than your last trade got vetoed.",
"Spewed everywhere. Dogshit ball security.",
"It's called rhythm, {T}. You mashed like a raccoon on a slot machine.",
"That splash zone had more return yards than your whole roster.",
"Puked foam all over the cheer squad. That's a lifetime ban in most states.",
"Your stomach just declined the trade. Hard."
],
DNF:[
"DNF. Did Not Fucking Finish. Like every season you've had.",
"Time's up and the shoe's still full. Just like your bench: full of useless shit.",
"Fifteen seconds and you couldn't finish one shoe. The league is ashamed.",
"That's a DNF, {T}. Sit down and think about your choices.",
"You quit on a beer. Your 2021 rookie class feels seen.",
"Ran out the clock with beer still in the shoe. Coward's kneel-down.",
"The shoe won. The shoe is now 1-0 against {T}.",
"Didn't finish. Add a shoey to the owed list and a clown to the logo.",
"Beer 1, {T} 0. Sad as hell.",
"Can't finish a beer, can't finish a season. Consistent, at least."
],
OFFBEAT:[
"{T} has worse rhythm than a holder on a botched field goal snap.",
"The whole stadium was stomping in time and you were tapping like a false start every play.",
"Off beat the entire shoey. You chug like your O-line pass blocks: late and confused.",
"The beat was right there, {T}. You missed it like a wide-open receiver.",
"Stomp, stomp, clap, and somehow {T} found the one count nobody was using.",
"Your timing is as bad as your trade timing: always a week late.",
"Zero rhythm. You'd jump offsides in a walkthrough."
],
ONBEAT:[
"On beat the whole way. Shame your lineup decisions never had that kind of timing.",
"{T} rode the stomp-clap like a pro. Rhythm of a drumline, roster of a JV squad.",
"Locked into the beat. First thing {T} has timed right since the startup draft.",
"Smooth chug, great rhythm, still a bum. The beat can't fix your RB room."
],
// Stiletto bank. Lines matching /Joe|rebuild|tank/i are only used for Joe's team.
J:[
"{T} chugging out of a glitter stiletto is still the best move this franchise made all year.",
"Year 6 of the rebuild, now featuring a sparkly heel full of warm beer.",
"The stiletto was the punishment. Your roster is the life sentence.",
"Even in a glitter heel, {T} found a way to lose.",
"That heel saw more action tonight than {T}'s starting lineup all season.",
"The stiletto is now the most valuable asset on {T}'s roster. By a mile.",
"Sip that glitter, {T}. It's the only shiny thing you're getting this decade.",
"Nobody would trade with you, so we gave you a high heel full of beer. Take the deal.",
"Rebuild status: still rebuilding. Vessel: stiletto. Dignity: traded for a 2029 4th.",
"You drank from a glitter heel and somehow it's not the most embarrassing thing on your roster.",
"That heel is four inches tall. Your playoff odds are smaller.",
"Joe, buddy. A stiletto shoey. The league has never been prouder to roast you.",
"Even the stiletto rejected your trade offer.",
"Glitter on your lips, foam on your chin, zero wins in your future.",
"That stiletto has a higher dynasty value than {T}'s entire QB room.",
"Congrats on finishing. The tank continues. The heel stays.",
"The rebuild just got pushed back another year. Blame the stiletto.",
"The cheerleaders aren't laughing with you, Joe. They have never once laughed with you.",
"Joe drinks from a heel and still can't get over the hump. Fitting.",
"{t}s out of a stiletto. Somewhere a 4th-round pick is prouder of you than we are.",
"Stiletto shoey, {T}. The beer went down easier than your last five losses. Barely."
]};
